name: deploying secrets

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v2

            - name: deploy secrets
              run: echo "The secret is ${{ secrets.API_KEY }}

